--- 
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
  emit:
    pattern:
      - /.+\.js.*$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    binary: './bin/terraform'
    use-cache: false
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
  npm:
    scripts: []
    dependencies:
      chai: 'latest'
  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~
  e2e:
    pattern:
      - /.+\.e2e\.js$/i
    screenshot:
      enabled: true
      take-on-fail: true
      path: './tests/e2e/screenshots'
    browsers:
      - firefox --headless

ec2_dev:
  root: './ec2'
  terraform:
    version: 0.11.0
    # test:
    #   plan: './tests/unit/'
    #   apply: './tests/e2e/'

# ec2_prod:
#   root: './ec2'
#   terraform:
#     version: 0.11.0

e2e:
 root: './tests/e2e/'

unit:
 root: './tests/unit/'
