---
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    cache: false
    plan: true
    apply: false
    destroy: false
    save-show-output: tfshow.txt
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
    test:
      plan: './tests/unit/'
      apply: './tests/e2e/'
      unit:
        mocha:
          options:
            ui: 'bdd'
            reporter: 'spec'
      e2e:
        testcafe:
          screenshot:
            enabled: true
            take-on-fail: true
            path: './tests/e2e/screenshots'
          browsers:
            - firefox --headless
  npm:
    scripts: []
    dependencies:
      chai: 'latest'
  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~
  e2e:
    testcafe:
      screenshot:
        enabled: true
        take-on-fail: true
        path: './tests/e2e/screenshots'
      browsers:
        - firefox --headless
    pattern:
      - /.+\.e2e\.js$/i
    ignore: ~

clarivate_admin_role:
  root: './iam_demo/roles/clarivate-admin-role'
  terraform:
    version: 0.11.0
    run-after:
      - clarivate_admin_policy
    var-files:
      - workspace.default.tfvars

clarivate_power_user_role:
  root: './iam_demo/roles/clarivate-power-user-role'
  terraform:
    version: 0.11.0
    run-after:
      - clarivate_power_user_policy
    var-files:
      - workspace.default.tfvars

clarivate_admin_policy:
  root: './iam_demo/policies/clarivate-admin-policy'
  terraform:
    version: 0.11.0
    var-files:
      - workspace.default.tfvars

clarivate_power_user_policy:
  root: './iam_demo/policies/clarivate-power-user-policy'
  terraform:
    version: 0.11.0
    var-files:
      - workspace.default.tfvars